### ISSUE TITLE
Mark Taken Status for Daily Medication

### ISSUE THREAD

**Issue by wenenhoe** [AY2324S2-CS2113T-T09-1/tp#19]
## User Story
As a user, I would like to indicate that I have taken a medication so that:
- I know when to take my next dose.
- I can keep track of how well I am following my doctors orders.
- I can show the doctor that I am taking my medications at the appropriate times of the day.

## Tasks
- [x] Low level code on implementing the data structures and methods to interact with (#20)
- [x] Command parsing to obtain user input (#40)
- [x] Connect user input with low level code (#54)
