### ISSUE TITLE
feat: Expand storage customisability

### ISSUE THREAD

**Issue by annoy-o-mus** [AY2324S2-CS2113T-T09-1/tp#29]
User Story: "As a user who likes to customise according to my preference, I want a configurable file and command so that I can modify statically/dynamically to my liking"

NFR - User Preference and setting should be persistent between sessions.
NFR - User should be given a choice to save a backup or archive their data before wiping existing data.

## Key Implementation
- [ ] Add support to save the historical data on the daily list of medicaion taken
- [ ] Add support for resetting the program
- [ ] Introduce basic configuration settings

## Future Possible Implementation
- Loading and Saving files in different formats
